services:
  postgres:
    image: postgres:15
    container_name: dadnovin-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YMCMBpass
      POSTGRES_DB: dadnovin_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: dadnovin-nextjs
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://postgres:YMCMBpass@postgres:5432/dadnovin_db"
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YMCMBpass
      POSTGRES_DB: dadnovin_db
      NEXTAUTH_SECRET: "supersecret"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data:
